sudo: false
dist: bionic

os:
 - linux
 - osx

language: d

d:
 - dmd-2.091.0
 - dmd-2.090.1
 - ldc-1.20.1
 - ldc-1.19.0
 - gdc
 - dmd-beta
 - ldc-beta
 - dmd
 - ldc

matrix:
  allow_failures:
   - os: osx
     d: gdc
   - d: dmd-beta
   - d: ldc-beta

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - hwloc

install:
 - if [ $TRAVIS_OS_NAME == osx ];
   then
     brew update;
     brew install openmpi;
   fi

script:
 - dub build :configure --compiler=${DC}
 - dub build :splice --compiler=${DC}
 - gen/setup.sh
 - dub test --compiler=${DC}
 - cd examples
 - for ex in $(ls -d *); do cd $ex; dub build --build=unittest --compiler=${DC}; mpirun -c 3 $(echo $ex | tr '[:upper:]' '[:lower:]'); cd ../; done
